In [1]:
# Core imports for the whole lab
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', None)
print('Setup complete. pandas', pd.__version__)

Setup complete. pandas 2.2.3

In [2]:
# -----------------------------------------------------------
# A DELIBERATELY MESSY DATASET (so the lab is self-contained)
# -----------------------------------------------------------
# Problems baked in: missing values, disguised missing ('N/A', -1),
# duplicate rows, a number stored as text, a date as text,
# an extreme outlier, and inconsistent city spellings.
raw = pd.DataFrame({
    'id':    [1, 2, 3, 4, 5, 6, 7, 7],
    'name':  ['Ana', 'Bo', 'Cy', 'Di', 'Eve', 'Fin', 'Gus', 'Gus'],
    'age':   [30, 25, np.nan, 41, -1, 38, 29, 29],
    'city':  [' Pune ', 'pune', 'DELHI', 'Delhi ', 'Mumbai', 'bombay', 'Pune.', 'Pune.'],
    'spend': ['120.5', '80.0', '200.2', 'N/A', '150.0', '99000', '110.0', '110.0'],
    'date':  ['2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
              '2024-01-09', '2024-01-10', '2024-01-11', '2024-01-11'],
})
raw

   id name   age    city  spend        date
0   1  Ana  30.0   Pune   120.5  2024-01-05
1   2   Bo  25.0    pune   80.0  2024-01-06
2   3   Cy   NaN   DELHI  200.2  2024-01-07
3   4   Di  41.0  Delhi     N/A  2024-01-08
4   5  Eve  -1.0  Mumbai  150.0  2024-01-09
5   6  Fin  38.0  bombay  99000  2024-01-10
6   7  Gus  29.0   Pune.  110.0  2024-01-11
7   7  Gus  29.0   Pune.  110.0  2024-01-11

In [4]:


df = raw.copy()        # always work on a copy
df.info()              # types + non-null counts

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      8 non-null      int64
 1   name    8 non-null      object
 2   age     7 non-null      float64
 3   city    8 non-null      object
 4   spend   8 non-null      object
 5   date    8 non-null      object
dtypes: float64(1), int64(1), object(4)
memory usage: 516.0+ bytes

In [5]:


print('Missing per column:')
print(df.isna().sum())
print('\nDuplicate rows:', df.duplicated().sum())
print('\nNote: spend is type', df['spend'].dtype, "-> stored as text!")

Missing per column:
id       0
name     0
age      1
city     0
spend    0
date     0
dtype: int64

Duplicate rows: 1

Note: spend is type object -> stored as text!

In [6]:

duplicate_count = df.duplicated().sum()
print("Duplicate rows:", duplicate_count)


missing_values = df.isnull().sum()
print("\nMissing values per column:")
print(missing_values)

Duplicate rows: 1

Missing values per column:
id       0
name     0
age      1
city     0
spend    0
date     0
dtype: int64

In [7]:

df['spend'] = pd.to_numeric(df['spend'], errors='coerce')  # 'N/A' -> NaN, text -> number
df['age']   = df['age'].replace(-1, np.nan)                # sentinel -> NaN

print('Missing after unmasking:')
print(df[['age', 'spend']].isna().sum())

Missing after unmasking:
age      2
spend    1
dtype: int64

In [8]:

df['age']   = df['age'].fillna(df['age'].median())
df['spend'] = df['spend'].fillna(df['spend'].median())
print('Missing after imputing:', df[['age', 'spend']].isna().sum().sum())

Missing after imputing: 0

In [9]:
ex = raw.copy()

1. unmask missing values (spend -> numeric, age -1 -> NaN)
ex["spend"] = pd.to_numeric(ex["spend"], errors="coerce")
ex["age"] = ex["age"].replace(-1, np.nan)

2a. dropna version
dropna_df = ex.dropna()

2b. median-impute version
impute_df = ex.copy()
impute_df["age"] = impute_df["age"].fillna(impute_df["age"].median())
impute_df["spend"] = impute_df["spend"].fillna(impute_df["spend"].median())

3. compare row counts
print("Original rows:", len(ex))
print("After dropna:", len(dropna_df))
print("After median imputation:", len(impute_df))

Original rows: 8
After dropna: 5
After median imputation: 8

In [10]:


print('Before:', df.shape)
df = df.drop_duplicates()
print('After :', df.shape, '-> removed the repeated Gus row')

Before: (8, 6)
After : (7, 6) -> removed the repeated Gus row

In [11]:


# 'date' is text -> convert to real datetimes so sorting/maths work
df['date'] = pd.to_datetime(df['date'])
# 'city' is a category -> mark it as such (saves memory, signals intent)
df['city'] = df['city'].astype('string')
print(df.dtypes)

id                int64
name             object
age             float64
city     string[python]
spend           float64
date     datetime64[ns]
dtype: object

In [12]:
ex = raw.copy()

ex["spend"] = pd.to_numeric(ex["spend"], errors="coerce")
ex["date"] = pd.to_datetime(ex["date"], errors="coerce")


ex = ex.drop_duplicates()


print("Data Types:")
print(ex.dtypes)

print("\nShape:")
print(ex.shape)

Data Types:
id                int64
name             object
age             float64
city             object
spend           float64
date     datetime64[ns]
dtype: object

Shape:
(7, 6)

In [13]:

q1, q3 = df['spend'].quantile([0.25, 0.75])
iqr = q3 - q1
low, high = q1 - 1.5 * iqr, q3 + 1.5 * iqr
print(f'Q1={q1:.1f}  Q3={q3:.1f}  IQR={iqr:.1f}')
print(f'Normal range: {low:.1f} to {high:.1f}')

outliers = df[(df['spend'] < low) | (df['spend'] > high)]
print('\nOutlier rows:')
print(outliers[['name', 'spend']])

Q1=115.2  Q3=175.1  IQR=59.8
Normal range: 25.5 to 264.9

Outlier rows:
  name    spend
5  Fin  99000.0

In [14]:

q1, q3 = df['spend'].quantile([0.25, 0.75])
iqr = q3 - q1
low, high = q1 - 1.5 * iqr, q3 + 1.5 * iqr
print(f'Q1={q1:.1f}  Q3={q3:.1f}  IQR={iqr:.1f}')
print(f'Normal range: {low:.1f} to {high:.1f}')

outliers = df[(df['spend'] < low) | (df['spend'] > high)]
print('\nOutlier rows:')
print(outliers[['name', 'spend']])



df['spend_capped'] = df['spend'].clip(lower=low, upper=high)
print(df[['name', 'spend', 'spend_capped']])

Q1=115.2  Q3=175.1  IQR=59.8
Normal range: 25.5 to 264.9

Outlier rows:
  name    spend
5  Fin  99000.0
  name    spend  spend_capped
0  Ana    120.5       120.500
1   Bo     80.0        80.000
2   Cy    200.2       200.200
3   Di    120.5       120.500
4  Eve    150.0       150.000
5  Fin  99000.0       264.875
6  Gus    110.0       110.000

In [15]:

Q1 = ex["age"].quantile(0.25)
Q3 = ex["age"].quantile(0.75)
IQR = Q3 - Q1

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)


outliers = ex[(ex["age"] < lower_bound) | (ex["age"] > upper_bound)]

print("Number of outlier rows:", len(outliers))
print(outliers)

Q1: 26.0
Q3: 36.0
IQR: 10.0
Lower Bound: 11.0
Upper Bound: 51.0
Number of outlier rows: 1
   id name  age    city  spend       date
4   5  Eve -1.0  Mumbai  150.0 2024-01-09

In [16]:


print(df['city'].value_counts())   # ' Pune ', 'pune', 'Pune.' all look different!

city
 Pune     1
pune      1
DELHI     1
Delhi     1
Mumbai    1
bombay    1
Pune.     1
Name: count, dtype: Int64

In [17]:


s = df['city'].astype('string')
s = s.str.strip()                       # trim whitespace
s = s.str.lower()                       # unify case
s = s.str.replace('.', '', regex=False) # drop stray punctuation
s = s.replace({'bombay': 'mumbai'})     # map known variants to one label
df['city'] = s
print(df['city'].value_counts())        # now clean categories

city
pune      3
delhi     2
mumbai    2
Name: count, dtype: Int64

In [18]:
messy = pd.Series(
    [' London ', 'london', 'LONDON', 'N.Y.', 'new york ', 'New York'],
    dtype='string'
)

clean = messy.str.strip().str.lower()


clean = clean.replace('n.y.', 'new york')


print(clean.value_counts())

london      3
new york    3
Name: count, dtype: Int64

In [19]:


clean = df.drop(columns=['spend_capped'])
print('Final shape:', clean.shape)
print('Missing values:', int(clean.isna().sum().sum()))
print('Duplicates    :', int(clean.duplicated().sum()))
clean

Final shape: (7, 6)
Missing values: 0
Duplicates    : 0

   id name   age    city    spend       date
0   1  Ana  30.0    pune    120.5 2024-01-05
1   2   Bo  25.0    pune     80.0 2024-01-06
2   3   Cy  29.5   delhi    200.2 2024-01-07
3   4   Di  41.0   delhi    120.5 2024-01-08
4   5  Eve  29.5  mumbai    150.0 2024-01-09
5   6  Fin  38.0  mumbai  99000.0 2024-01-10
6   7  Gus  29.0    pune    110.0 2024-01-11